version: '3'

services:
  
  # Setup node container
  backend: 
    build: ./backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes: 
      - ./backend/src:/app/weatherapp-backend/src
    command: npm run dev
  
  # Setup react container
  frontend:
    build: ./frontend
    expose:
      - ${APP_CLIENT_PORT}
    environment:
      - APP_CLIENT_PORT=${APP_CLIENT_PORT}
    ports:
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    volumes:
      - ./backend/src:/app/weatherapp-backend/src
      - ./frontend/src:/app/weatherapp-frontend/src
    links:
      - backend
    command: npm run start
